---

- name: install heartbeat
  package:
    name: heartbeat
    state: installed

- name: authkeys
  copy:
    src: "{{ playbook_dir }}/templates/{{ heartbeat_authkeys }}"
    dest: /etc/ha.d/authkeys
    backup: yes
  notify: reload heartbeat

- name: ha.cf
  copy:
    src: "{{ playbook_dir }}/templates/{{ heartbeat_ha }}"
    dest: /etc/ha.d/ha.cf
    backup: yes
  notify: reload heartbeat

- name: haresources
  copy:
    src: "{{ playbook_dir }}/templates/{{ heartbeat_haresources }}"
    dest: /etc/ha.d/haresources
    backup: yes
  notify: reload heartbeat

- name: start heartbeat
  service:
    name: heartbeat
    enabled: yes
    state: started
